### ISSUE TITLE
Colourco.de won't load in Google Chrome

### ISSUE THREAD

**Issue by tristandoo** [Zaku-eu/colourco.de#34]
Every time I try to go to http://colourco.de/ it won't load using Chrome (like it has in the past), but if I use Internet Explorer (yuck) it works just fine...

**Comment by Tonkonozhenko** [comment]
+1

**Comment by Zaku-eu** [comment]
tomorrow i take a look why its broken right now

**Comment by Zaku-eu** [comment]
should be fixed now =)
